### ISSUE TITLE
Support input of program from text file

### ISSUE THREAD

**Issue by chrisjbris** [chrisjbris/llvm-debugy#2]

**Comment by OCHyams** [comment]
Parser / encoder added in https://github.com/chrisjbris/llvm-debugy/pull/9/files
There are a few FIXMEs and TODOs but it broadly works.

Operands of type `OperandType::variable` (variable width ints with byte-widths specified by previous operand) are not yet implemented (so we can't yet encode `DW_OP_implicit_value`, `DW_OP_entry_value`, or `DW_OP_const_type`).

Assumed 32-bit mode for now as AFAIK this is the expected/standard version (should this be adjusted by a flag?). Assume 64-bit addresses for now, again as what seems like the sensible default.

As the commit message says, there could probably be less code. But it does the job.
